import type { HltbEntry, HltbSection } from '../types';

// Bundled offline index generated by scripts/build-hltb.mjs
// eslint-disable-next-line @typescript-eslint/no-var-requires
const raw = require('../../assets/hltb/index.json') as {
  sections: HltbSection[];
  entries: HltbEntry[];
  costWeights: unknown;
  source: string;
};

const EVIDENCE_RANK: Record<string, number> = { A: 0, B: 1, C: 2 };
const TIER_RANK: Record<string, number> = { 极高: 0, 高: 1, 一般: 2 };

export type SafetyKind = 'emergency' | 'suicide' | 'legal' | null;

export type SearchHit = HltbEntry & { score: number };

const STOP = new Set([
  '的',
  '了',
  '吗',
  '呢',
  '啊',
  '是',
  '我',
  '你',
  '他',
  '她',
  '它',
  '和',
  '与',
  '或',
  '在',
  '有',
  '没有',
  '一个',
  '什么',
  '怎么',
  '如何',
  '哪些',
  '这个',
  '那个',
  '一下',
  '可以',
  '应该',
  '要不要',
  '该不该',
  '划不划算',
  '值不值',
]);

export function getSections(): HltbSection[] {
  return raw.sections;
}

export function getSourceUrl(): string {
  return raw.source;
}

export function detectSafety(question: string): SafetyKind {
  const q = question.toLowerCase();
  if (
    /自杀|不想活|活不下去|结束生命|自我了断|割腕|跳楼/.test(q)
  ) {
    return 'suicide';
  }
  if (
    /没呼吸|大出血|火灾|溺水|触电|中毒|心梗|胸痛|卒中|中风|呼救|倒地/.test(q)
  ) {
    return 'emergency';
  }
  if (/被传唤|被拘留|被起诉|刑事拘留|看守所|检察院|法院传票/.test(q)) {
    return 'legal';
  }
  return null;
}

export function safetyPreface(kind: SafetyKind): string | null {
  if (kind === 'emergency') {
    return '若正在发生急症：先打 120 / 119，并按现场第一个救命动作处理。出处见第 13 节。下面若继续，只作补充，不能代替急救。';
  }
  if (kind === 'suicide') {
    return '如果你正在经历强烈痛苦：请先联系全国心理援助热线 12356。下面只按书中相关条目作通用参考，不做劝导式分析。';
  }
  if (kind === 'legal') {
    return '若你已在法律程序中（传唤、拘留、起诉等）：书只给通用口径，个案请尽快找律师。下面条目不能替代专业辩护。';
  }
  return null;
}

function tokenize(input: string): string[] {
  const normalized = input.toLowerCase().replace(/[^\u4e00-\u9fff\w]+/g, ' ');
  const parts = normalized
    .split(/\s+/)
    .flatMap((chunk) => {
      if (!chunk) return [];
      if (/[\u4e00-\u9fff]/.test(chunk)) {
        const grams: string[] = [];
        if (chunk.length <= 2) grams.push(chunk);
        for (let i = 0; i < chunk.length - 1; i++) {
          grams.push(chunk.slice(i, i + 2));
          if (i + 3 <= chunk.length) grams.push(chunk.slice(i, i + 3));
        }
        return grams;
      }
      return [chunk];
    })
    .filter((t) => t.length >= 2 && !STOP.has(t));
  return Array.from(new Set(parts));
}

function sectionBoost(question: string, section: HltbSection): number {
  const q = question.toLowerCase();
  let score = 0;
  const hay = `${section.title} ${section.question}`.toLowerCase();
  for (const token of tokenize(question)) {
    if (hay.includes(token)) score += 4;
  }
  // light topic hints
  const hints: Array<[RegExp, number[]]> = [
    [/拖延|时间|截止|开会|任务拆/, [4]],
    [/钱|理财|利息|骗局|智商税/, [5, 6]],
    [/担保|借条|彩礼|转账|报案|律师/, [8, 9]],
    [/恋爱|结婚|领证|异地/, [10]],
    [/租房|房东|押金|买房/, [15]],
    [/失业|欠薪|低保|没钱/, [7]],
    [/加班|裁员|工伤|年假/, [19]],
    [/急症|急救|火灾|溺水/, [13]],
    [/账号|被盗|手机丢/, [14]],
    [/抽烟|喝酒|熬夜|久坐|运动/, [1, 2]],
    [/创业|开店|公司/, [12]],
    [/孩子|育儿|上学/, [18, 20, 30]],
    [/抑郁|打击|崩溃/, [29]],
  ];
  for (const [re, nos] of hints) {
    if (re.test(q) && nos.includes(section.sectionNo)) score += 8;
  }
  return score;
}

export function searchEntries(question: string, limit = 8): SearchHit[] {
  const tokens = tokenize(question);
  if (!tokens.length) return [];

  const sectionScores = new Map<number, number>();
  for (const section of raw.sections) {
    sectionScores.set(section.sectionNo, sectionBoost(question, section));
  }

  const rankedSections = [...sectionScores.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .filter(([, s]) => s > 0)
    .map(([no]) => no);

  const pool =
    rankedSections.length > 0
      ? raw.entries.filter((e) => rankedSections.includes(e.sectionNo))
      : raw.entries;

  const hits: SearchHit[] = [];
  for (const entry of pool) {
    let score = sectionScores.get(entry.sectionNo) ?? 0;
    const title = entry.title.toLowerCase();
    const body = entry.body.toLowerCase();
    for (const token of tokens) {
      if (title.includes(token)) score += 6;
      else if (body.includes(token)) score += 2;
    }
    if (score <= 0) continue;
    hits.push({ ...entry, score });
  }

  hits.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    if (a.tags.axis !== b.tags.axis) return a.tags.axis.localeCompare(b.tags.axis);
    const tier = (TIER_RANK[a.ratioTier] ?? 3) - (TIER_RANK[b.ratioTier] ?? 3);
    if (tier !== 0) return tier;
    return (EVIDENCE_RANK[a.evidence] ?? 3) - (EVIDENCE_RANK[b.evidence] ?? 3);
  });

  // Keep axes separate but return a flat top-N for prompting
  return hits.slice(0, limit);
}

export function formatCitation(entry: HltbEntry): string {
  return `第 ${entry.sectionNo} 节第 ${entry.entryNo} 条（${entry.title}）`;
}

export function emptyBookAnswer(question: string): string {
  return [
    '书里没写到这件事。',
    '',
    `你问的是：「${question.trim()}」。我在《高性价比人生指南》本地索引里没有捞到足够相关的条目，所以不能按书里的数字或法条下结论。`,
    '',
    '常识判断（不是书里的内容）：可以把问题拆小、写清约束（钱/时间/风险），再决定要不要找医生、律师或其他专业人士。',
    '',
    `原书：${raw.source}`,
  ].join('\n');
}
